# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageCourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='studens',
            field=models.ManyToManyField(to='manageCourse.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manageCourse.Teacher'),
            preserve_default=False,
        ),
    ]
